name: Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: aws-budget-terraform
  cancel-in-progress: false

jobs:
  terraform:
    uses: KandlerLi/gha-common/.github/workflows/terraform-apply.yml@v0.0.2
    with:
      aws_region: us-east-1
      extra_repo_vars: "ALERT_EMAIL"
    secrets: inherit
